# Generated by Django 3.2 on 2023-01-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=120)),
                ('flavour', models.CharField(max_length=120)),
                ('units', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cocoa_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diet_type', models.CharField(blank=True, max_length=120, null=True)),
                ('speciality', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.CharField(max_length=120)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
